version: 2.1
jobs:
  build-app:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
  steps:
    - checkout
    - run:
        name: Start server
        command: |
          export FLASK_APP=project/__init__.py
          export FLASK_ENV=development
          python manage.py run

workflows:
  main:
    jobs:
      - build-app